### ISSUE TITLE
cargo clippy --fix mishandles order of operations [neg_multiply]

### ISSUE THREAD

**Issue by bazald** [rust-lang/rust-clippy#15340]
### Summary

`cargo clippy --fix --workspace -- -W clippy::all` consistently fails to respect order of operations, resulting in changes to the semantics and output of the mathematical expressions.

### Reproducer

Simply demonstrated in [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=99baf7edb1fca4a80cbd1a729a3b8469), running Clippy not withstanding:

```rust
    let math_result = (-1.0 * (2.0f64 - 3.0f64)).exp();
    let expected_result = 1.0f64.exp(); 
    assert_eq!(math_result, expected_result);
```

run through `cargo clippy --fix --workspace -- -W clippy::all` becomes

```rust
    let math_result = -(2.0f64 - 3.0f64).exp();
    let expected_result = 1.0f64.exp(); 
    assert_eq!(math_result, expected_result);
```

The second `assert_eq` fails as follows:
```
thread 'main' panicked at src/main.rs:8:5:
assertion `left == right` failed
  left: -0.36787944117144233
 right: 2.718281828459045
```

### Version

```text
Clippy
Catch common mistakes and improve the code using the Clippy linter.
0.1.88 (2025-06-23 6b00bc3880)

rustc 1.88.0 (6b00bc388 2025-06-23)
binary: rustc
commit-hash: 6b00bc3880198600130e1cf62b8f8a93494488cc
commit-date: 2025-06-23
host: aarch64-apple-darwin
release: 1.88.0
LLVM version: 20.1.5
```

### Additional Labels

@rustbot label +l-suggestion-causes-error

**Comment by bazald** [comment]
Possibly related to https://github.com/rust-lang/rust-clippy/issues/4735

**Comment by ComputerDruid** [comment]
I think this was already fixed in https://github.com/rust-lang/rust-clippy/pull/15179

I was able to reproduce the issue on stable, but see correct behavior on nightly:

```
❯ clippy-driver +nightly -Vv
rustc 1.90.0-nightly (ace633090 2025-07-23)
binary: rustc
commit-hash: ace633090349fc5075b5b0d56294de985e7d1191
commit-date: 2025-07-23
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.8
```

**Comment by bazald** [comment]
Interesting. Yeah, not fixed yet in beta either, but does add the extra needed parens in nightly.
